### PR TITLE
Rename internal database to prisma

### PR DESCRIPTION
**Pull request by dpetrick**

### CODE REVIEW

**Comment by marktani** [comment]
Can we roll this out, @timsuchanek @dpetrick? 🙂

**Comment by Fi1osof** [comment]
So how can i change MySQL password on local prisma project? Or set custom password for all prisma?
Thanks.

**Comment by chj-damon** [comment]
@marktani @Fi1osof so what's it now? can I change MySQL password or rename the database now?

**Comment by dpetrick** [comment]
Closing this PR in favour of https://github.com/graphcool/prisma/pull/2254

**Comment by Fi1osof** [comment]
@chj-damon i still not know how. Total silence.

**Comment by marktani** [comment]
Hey @chj-damon @Fi1osof, sorry for missing your questions 🙂For future reference, please ask questions in new issues or threads [in the Forum](https://www.graph.cool/forum/c/questions), it's easy to miss messages on PRs and closed issues 🙌 

The user and password is determined by the `docker-compose.yml` file, so you can change it there if you want to 🙂[Here's](https://www.prisma.io/docs/reference/upgrade-guides/upgrading-prisma/upgrade-to-1.7-iquaecuj6b) an example.

**Comment by Fi1osof** [comment]
@marktani , yes, i asked in feb https://www.graph.cool/forum/t/custom-mysql-password-for-prisma-local/2509
Received your reply 11 days before, but not seen notify.
Thanks!

**Pull request closed without merging**
