### PR TITLE
Upsert arguments are always in order resolves #1761

### LINKED ISSUE #1761: Upsert fails with parameters out of order
After writing an upsert mutation, I was surprised to see a 500 from the Prisma server. Looking in the Docker logs, it seems like the parameters for the SQL query are not relayed in order. Specifically, the `type` variable is being assigned to the `id` field in the database, which triggers a uniqueness constraint error.

It appears that `type` is getting pushed to the end of the SELECT clause parameters, even though it's listed as the 4th parameter in the INSERT clause. Could it be related to type being a custom enum, or maybe even its position in the original schema definition?

Type definition:

```
type Permission {
  id: ID! @unique
  name: String! @unique
  crudKey: String! @unique
  type: PermissionType!

  resourceName: String
  allowedOperation: CrudOperation

  customOperation: CustomOperation @relation(name: "CustomOperationOnPermission")

  users: [User!]! @relation(name: "UserOnPermissions")
  groups: [PermissionGroup!]! @relation(name: "PermissionGroupOnPermissions")
}
```

Query:

```js
const permission = {
  resourceName: 'Node',
  allowedOperation: 'UPDATE',
  key: 'Node:UPDATE'
};

context.db.mutation.upsertPermission({ 
  create: {
    name: permission.key,
    crudKey: permission.key,
    type: 'CRUD',
    resourceName: permission.resourceName,
    allowedOperation: permission.allowedOperation,
  },
  update: {
    resourceName: permission.resourceName,
    allowedOperation: permission.allowedOperation,
  },    
  where: {     
    crudKey: permission.key,
  },
})
```

Error in Docker logs:

```
[Bugsnag - local / testing] Error report: com.bugsnag.Report@32174158
Caused by: java.sql.SQLException: Duplicate entry 'CRUD' for key 'PRIMARY'
Query is: INSERT INTO `prisma-admin@dev`.`Permission` ( `name` , `allowedOperation` , `crudKey` , `type` , `resourceName` , `id` ) SELECT  ? , ? , ? , ? , ? , ? FROM DUAL where not exists (
select `id` from `prisma-admin@dev`.`Permission` where `crudKey` = ? limit 1);, parameters ['Node:UPDATE','UPDATE','Node:UPDATE','Node','cjcznwwpu00ce01675iv1ijqf','CRUD','Node:UPDATE']
        at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:146)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:217)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:218)
        ... 24 more
java.sql.SQLIntegrityConstraintViolationException: (conn=37) Duplicate entry 'CRUD' for key 'PRIMARY'
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:157)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:106)
        at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:235)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:224)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:159)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
        at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:39)
        at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
        at slick.jdbc.Invoker.first(Invoker.scala:31)
        at slick.jdbc.Invoker.first$(Invoker.scala:30)
[Bugsnag - local / testing] Error report: com.bugsnag.Report@66ca7960
        at slick.jdbc.StatementInvoker.first(StatementInvoker.scala:16)
        at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:52)
        at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:51)
        at slick.dbio.DBIOAction$$anon$4.$anonfun$run$3(DBIOAction.scala:240)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:240)
        at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:238)
        at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:240)
        at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:240)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[Bugsnag - local / testing] Error report: com.bugsnag.Report@3aa0309c
Caused by: java.sql.SQLException: Duplicate entry 'CRUD' for key 'PRIMARY'
Query is: INSERT INTO `prisma-admin@dev`.`Permission` ( `name` , `allowedOperation` , `crudKey` , `type` , `resourceName` , `id` ) SELECT  ? , ? , ? , ? , ? , ? FROM DUAL where not exists (
select `id` from `prisma-admin@dev`.`Permission` where `crudKey` = ? limit 1);, parameters ['Node:DELETE','DELETE','Node:DELETE','Node','cjcznwwro00cn0167tc089duu','CRUD','Node:DELETE']
        at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:146)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:217)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:218)
        ... 24 more
```

### PR DESCRIPTION
**Pull request by seanchambo**
Cannot currently upsert reliably as the keys and values returned for the create are sometimes out of order

### CODE REVIEW

**Comment by do4gr** [comment]
Hey @seanchambo thanks for the contribution. It looks good! Could you please also add a test with several arguments? I know that the failures don't happen all the time, but it would be nice to have a test covering this anyways. The test file is the UpsertMutationSpec. 

If you have trouble with the test syntax I can also later add the test before I merge it.

**Comment by seanchambo** [comment]
I'll give it a shot @do4gr and let you know how I go. If I get stuck with anything I'll let you know.

**Comment by do4gr** [comment]
tests added in this pr https://github.com/graphcool/prisma/pull/1843

**Comment by mavilein** [comment]
Thank you @seanchambo !

**Pull request merged**
