### PR TITLE
[WIP] Prisma

### PR DESCRIPTION
**Pull request by mavilein**
### Overview

This PR acts as a roadmap for the Graphcool 1.0 beta over the following weeks.
Subscribe to get updates when new features or examples are released throughout the beta.

You can find more general information about Graphcool 1.0 in the [announcement blog post](https://medium.com/@graphcool/c1d4981383d9), also check out [these GraphQL boilerplate examples](https://github.com/grapqhl-boilerplates) to get started, as well as the updated [reference documentation](https://www.graph.cool/docs/1.0/reference/).

This [Forum thread](https://www.graph.cool/forum/t/developer-preview-graphcool-1-0-beta/1891?u=nilan) is the best place to provide feedback and discuss questions.

Thanks a lot for your participation 💚 

### Feature Roadmap

As we are preparing for the 1.0 release, new features will be released roughly once a week.

<details>
<summary>Version Scheme</summary>

Both the CLI and the Server are using the following version scheme `1.0.0-betaA.B` during the beta. `A` is incremented for feature releases, and `B` is incremented inbetween, for ongoing improvements. For hotfixes, `.C` is appended. Hotfixes are incremented individually for CLI and Server.

##### Examples

* `1.0.0-beta1` - first feature release
* `1.0.0-beta1.2` - improvements have been released after the first and before the second feature release
* `1.0.0-beta1.2.3` - three hotfixes have been released in the CLI, while the Server is still running on `1.0.0-beta1.2.1`, because only one hotfix has been released for the Server.
</details>

#### beta1

- [x] Query API #1340
- [x] Improved API for nested mutations #1280
- [x] Data Import #1299 
- [x] New `graphcool.yml` format #1328
- [x] Deployment targets should be service name instead of generated service ID #1329
- [x] Cluster Version #1376 
- [x] Changes to SDL #1380 

#### beta2

- [x] Generated type names #1341
- [x] updateMany & deleteMany #81
- [x] Basic Database seeding #1181
- [x] New CLI commands layout #1330
- [x] Reference by any unique field #1267

<details>
<summary>Release Notes</summary>

We just released `graphcool@1.0.0-beta2` 🎉 

### Features & Changes

* You can now [update or delete many nodes at once](https://github.com/graphcool/framework/issues/81) using the `updateMany` and `deleteMany` mutations. This is how it could look like for an `deleteManyUsers` mutation:

  ```graphql
  mutation {
    deleteManyUsers(
      where: {
        email_contains: "@graph.cool"
      }
    )
  }
  ```
* Data export and import has been added according to [this proposal](https://github.com/graphcool/framework/issues/1299), you can use it with `graphcool export` and `graphcool import`.

  With the [latest `graphcool-framework` version](https://github.com/graphcool/framework/releases/tag/0.11.4), you can now export data and import it into a service of the 1.0 preview:

  ```sh
  graphcool-framework export -e export.zip
  graphcool import --source export.zip --stage dev
  ```

* Additionally to importing data, you can seed your service with initial data using `graphcool seed`. This is useful for CI, or to get a development stage up and running quickly. More information can be found [here](https://github.com/graphcool/framework/issues/1181).
* You can now [reference existing nodes by any unique field](https://github.com/graphcool/framework/issues/1267) whenever possible. This is how it could look like for an `updateUser` mutation:

  ```graphql
  mutation {
    updateUser(
      where: {
        email: "nilan@graph.cool"
      }
      data: {
        name: "Nilan"
      }
    )
  }
  ```

* The CLI comes with an revisited [command layout](https://github.com/graphcool/framework/issues/1330).

### Getting the latest preview version

* Get the latest CLI version with `npm install -g graphcool@beta`
* Then, upgrade your Docker containers using `graphcool local upgrade`

### Notes

* **All services have been removed from the `shared-public-demo` cluster**, due to changes to the underlying structure of the database.
* As a reminder, **all deployed services to the `shared-public-demo` cluster are completely publically available** until proper [cluster authentication](https://github.com/graphcool/framework/issues/1365) is released to the beta. This includes access to the data, as well as to the service itself.
* If you run into errors or problems with a deployment to the `local` cluster, try running `graphcool local nuke` to **completely wipe your Docker containers including all data**. Then try again 🙂

### Resources & Feedback

We added boilerplate examples for [Node](https://github.com/graphql-boilerplates/node-graphql-server) and [TypeScript](https://github.com/graphql-boilerplates/typescript-graphql-server), go check them out 🙌  The [reference documentation](https://www.graph.cool/docs/1.0/reference/) is continuously being updated as well.

If you have any questions or want to provide feedback, please [join the discussion in the Forum](https://www.graph.cool/forum/t/developer-preview-graphcool-1-0-beta/1891?u=nilan).

To report a bug, please use the [issue tracker](https://github.com/graphcool/framework).

</details>

#### beta3

- [x] Direct database access #1375
- [x] Advanced Database seeding #1181
- [x] Improved service deployment reliability #595
- [x] Transactional nested mutations #1280
- [x] Subscriptions
- [x] Error Handling
- [x] Non-null fields #1382
- [x] Embedded Types #1160 
- [x] More powerful scalar lists (data structure) #1275 

#### beta4

- [x] Delete service mutation #1415
- [x] Move resetData mutation to private API
- [x] CLI `login` command #1365
- [x] fix RelayIds Table to not reference model names 
- [x] New API endpoints #1417
- [x] Serverside Subscriptions
- [x] Subscriptions in hosted Playground

<details>
<summary>Release Notes</summary>

### Features & Changes

* **Transactional nested mutations**

  This means that if a single mutation fails (for example, due to a violated unique constraint), _all_ mutations part of the nested mutation are not executed. Read [this specification](https://github.com/graphcool/framework/issues/1280) for details.

* **Embedded Types and Optional Relation Directives**

  You can now define unidirectional relations, which enables embedded types. This is now a valid datamodel:

  ```graphql
  type User {
    id: ID! @unique
    name: String!
    location: Location
    friends: [User!]! @relation(name: "Friends")
  }

  type Location {
    lat: Float!
    lng: Float!
    city: City
  }

  type City {
    name: String!
  }
  ```

  * **Optional Relation Directives:** Note that `location: Location` and `city: City` doesn't have a `@relation` directive.
  * **Unidirectional relations:** Note that `Location` doesn't have a field of type `User`, and `City` doesn't have a field of type `Location`.

* **Subscription support**

  The Subscription API is hosted at the same endpoints the DB API, but with the `wss` protocol instead. You can check [the Graphcool Server example](https://github.com/graphcool/graphcool-server-example) to see how to expose subscriptions using `graphcool-binding`.

* **Deployment improvements**

  * **Deployment resilience:** All known problems that made deployment stuck have been fixed.
  * **Deployment Progress Feedback:** You'll now receive incremental feedback during a deployment progress:

  ```sh
  Applying changes (215/317) ⡿
  ```

* **Completely rehauled CLI commands**

  Run `graphcool` to see the new command layout. Two examples:

  * the `graphcool token` command was added, which generates a service token for the current token
  * `graphcool cluster` commands let you interact with & manage your clusters.

* **GraphQL compliant error handling**

  API errors now return a GraphQL compliant response, including an error code and a developer-friendly error message.

* **Advanced database seeding**

  You can now seed a service upon first deploy using a `.graphql` file as [further described here](https://github.com/graphcool/framework/issues/1181). Check [the Graphcool Server example](https://github.com/graphcool/graphcool-server-example) to see how this looks like in practice.

* **Clusters and Stages**

  We have re-introduced the _cluster_ and _stage_ properties in `graphcool.yml` as described [here](https://github.com/graphcool/framework/issues/1461). This might require a change in the `graphcool.yml` file you're currently using. Simply add a `stage` property like so:

  ```diff
  # graphcool.yml
  service: graphql-boilerplate

  + stage: dev

  datamodel: database/datamodel.graphql

  disableAuth: true
  ```

* **General stability improvements**

  Thanks to the great help and feedback we've received since the last beta release, we were able to iron out a bunch of issues. Thanks a lot :pray:

### Upgrading to beta4

* First, export your data `graphcool export -e export.zip`
* Get the latest CLI version with `npm install -g graphcool@beta`
* Then, upgrade your Docker containers using `graphcool local upgrade`
* Because of changes to the underlying data structure, you need to **completely wipe your Docker containers including all data** with `graphcool local nuke`
* Then, deploy your service again using `graphcool deploy`. You'll be prompted to choose a cluster.
* Now import the previously exported data `graphcool import -d export.zip`

### Notes

* As a reminder, **all deployed services to the `shared-public-demo` cluster are completely publically available**. The same is true for _public_ deployments to `graphcool-eu1` and `graphcool-us1`. However, for _private_ deployments (after logging in), proper [cluster authentication](https://github.com/graphcool/framework/issues/1365) is set in place, that protects both your data and services from outside access, if protected with a secret as described in the feature request.

### Resources & Feedback

* All **boilerplate examples** have been updated to the latest beta release. You can get started like this:

```sh
npm install -g graphql-cli
graphql create my-app
# choose a boilerplate and follow along the instructions
```

* The **[reference documentation](https://www.graph.cool/docs/1.0/reference/)** is continuously being updated as well.

If you have any questions or want to provide feedback, please [join the discussion in the Forum](https://www.graph.cool/forum/t/developer-preview-graphcool-1-0-beta/1891?u=nilan).

To report a bug, please use the [issue tracker](https://github.com/graphcool/graphcool).
</details>

#### beta5

- [x] validation of queries for Serverside Subscriptions
- [x] Bug: handle 63 character limit on table names in MySQL (for Relations)
- [x] Count query
- [x] Subscriptions: Authentication

#### post 1.0 release

- [ ] More powerful scalar lists (API) #1275 
- [ ] Cascading Deletes #1262 
- [ ] Aggregations #1312
- [ ] Bring your own id, createdAt, updatedAt #1278 
- [ ] Index support #1300
- [ ] Interfaces and Polymorphic relations #83
- [ ] Filter on aggregated values #1279
- [ ] Migration based deployment #1263
- [ ] Atomic Operations #1349
- [ ] Request logs #749

### Resources

We are adding examples and guides that illustrate common use cases. Please write a comment if there is a specific example you would like to see 🙂 

#### Examples

* [x] [Boilerplate](https://github.com/graphcool/graphql-boilerplate) (covering many of the following topics)
* [ ] Graphcool Binding
* [ ] Resolvers
* [ ] REST API wrapper
* [ ] Serverless integration
* [x] [File Handling](https://github.com/maticzav/graphql-server-file-upload-example)
* [ ] Authentication
* [ ] Authorization (also see https://github.com/graphcool/graphcool-binding/issues/8)
* [ ] Subscriptions

#### Guides

* [ ] Data import/export
* [ ] Upgrade projects to Graphcool 1.0
* [ ] Deployment https://github.com/graphcool/framework/issues/1350

### CODE REVIEW

**Comment by marktani** [comment]
## beta2

We just released `graphcool@1.0.0-beta2` 🎉 

### Features & Changes

* Data export and import has been added according to [this proposal](https://github.com/graphcool/framework/issues/1299), you can use it with `graphcool export` and `graphcool import`.
* Additionally to importing data, you can seed your service with initial data using `graphcool seed`. This is useful for CI, or to get a development stage up and running quickly. More information can be found [here](https://github.com/graphcool/framework/issues/1181).
* You can now [reference existing nodes by any unique field](https://github.com/graphcool/framework/issues/1267) whenever possible. This is how it could look like for an `updateUser` mutation:

  ```graphql
  mutation {
    updateUser(
      where: {
        email: "nilan@graph.cool"
      }
      data: {
        name: "Nilan"
      }
    )
  }
  ```

* You can now [update or delete many nodes at once](https://github.com/graphcool/framework/issues/81) using the `updateMany` and `deleteMany` mutations. This is how it could look like for an `deleteManyUsers` mutation:

  ```graphql
  mutation {
    deleteManyUsers(
      where: {
        email_contains: "@graph.cool"
      }
    )
  }
  ```

* The CLI comes with an revisited [command layout](https://github.com/graphcool/framework/issues/1330).

### Getting the latest preview version

* Get the latest CLI version with `npm install -g graphcool@beta`
* Then, upgrade your Docker containers using `graphcool local upgrade`

### Notes

* **All services have been removed from the `shared-public-demo` cluster**, due to changes to the underlying structure of the database.
* As a reminder, **all deployed services to the `shared-public-demo` cluster are completely publically available** until proper [cluster authentication](https://github.com/graphcool/framework/issues/1365) is released to the beta. This includes access to the data, as well as to the service itself.
* If you run into errors or problems with a deployment to the `local` cluster, try running `graphcool local nuke` to **completely wipe your Docker containers including all data**. Then try again 🙂


### Resources & Feedback

We added boilerplate examples for [Node](https://github.com/graphql-boilerplates/node-graphql-server) and [TypeScript](https://github.com/graphql-boilerplates/typescript-graphql-server), go check them out 🙌  The [reference documentation](https://www.graph.cool/docs/1.0/reference/) is continuously being updated as well.

If you have any questions or want to provide feedback, please [join the discussion in the Forum](https://www.graph.cool/forum/t/developer-preview-graphcool-1-0-beta/1891?u=nilan).

To report a bug, please use the [issue tracker](https://github.com/graphcool/framework).

**Comment by kbrandwijk** [comment]
Your comment mentions
> Get the latest CLI version with npm install -g graphcool@beta

But I read it has been renamed to `graphcool-framework`.

**Comment by marktani** [comment]
@kbrandwijk I updated [the release notes](https://github.com/graphcool/framework/releases/tag/0.11.4) to clarify the situation of binary changes for the Framework CLI and the Graphcool 1.0 CLI. Thanks! 🙂

**Comment by philcockfield** [comment]
>> Please write a comment if there is a specific example you would like to see 🙂

A data migration example would be useful.

**Comment by LFP6** [comment]
Currently the docs link to [this blog post](https://blog.graph.cool/graphql-sdl-schema-definition-language-6755bcb9ce51) describing SDL, but it is getting increasingly out of date. Will we see it included directly in the docs? Seems like they're missing a fair amount of API information in general (I keep needing to look through GitHub issues and PRs to know what's currently implemented). I'm assuming this will be improved as time goes on, and I may be interested in contributing to that as it would be a great usability improvement (if I can find the time, which is always the trouble).

**Comment by marktani** [comment]
@philcockfield are you talking about data export/import workflows or something else? 🙂 
@LFP6 thanks for your feedback! [This part of the documentation](https://www.graph.cool/docs/1.0/reference/database/data-modelling-(sdl)-eiroozae8u) described the data modeling capabilities. The blog post is a general introduction to SDL.

**Comment by marktani** [comment]
## beta4

We just released `graphcool@1.0.0-beta4` 🎉

### Features & Changes

* **Transactional nested mutations**

  This means that if a single mutation fails (for example, due to a violated unique constraint), _all_ mutations part of the nested mutation are not executed. Read [this specification](https://github.com/graphcool/framework/issues/1280) for details.

* **Embedded Types and Optional Relation Directives**

  You can now define unidirectional relations, which enables embedded types. This is now a valid datamodel:

  ```graphql
  type User {
    id: ID! @unique
    name: String!
    location: Location
    friends: [User!]! @relation(name: "Friends")
  }

  type Location {
    lat: Float!
    lng: Float!
    city: City
  }

  type City {
    name: String!
  }
  ```

  * **Optional Relation Directives:** Note that `location: Location` and `city: City` doesn't have a `@relation` directive.
  * **Unidirectional relations:** Note that `Location` doesn't have a field of type `User`, and `City` doesn't have a field of type `Location`.

* **Subscription support**

  The Subscription API is hosted at the same endpoints the DB API, but with the `wss` protocol instead. You can check [the Graphcool Server example](https://github.com/graphcool/graphcool-server-example) to see how to expose subscriptions using `graphcool-binding`.

* **Deployment improvements**

  * **Deployment resilience:** All known problems that made deployment stuck have been fixed.
  * **Deployment Progress Feedback:** You'll now receive incremental feedback during a deployment progress:

  ```sh
  Applying changes (215/317) ⡿
  ```

* **Completely rehauled CLI commands**

  Run `graphcool` to see the new command layout. Two examples:

  * the `graphcool token` command was added, which generates a service token for the current token
  * `graphcool cluster` commands let you interact with & manage your clusters.

* **GraphQL compliant error handling**

  API errors now return a GraphQL compliant response, including an error code and a developer-friendly error message.

* **Advanced database seeding**

  You can now seed a service upon first deploy using a `.graphql` file as [further described here](https://github.com/graphcool/framework/issues/1181). Check [the Graphcool Server example](https://github.com/graphcool/graphcool-server-example) to see how this looks like in practice.

* **Clusters and Stages**

  We have re-introduced the _cluster_ and _stage_ properties in `graphcool.yml` as described [here](https://github.com/graphcool/framework/issues/1461). This might require a change in the `graphcool.yml` file you're currently using. Simply add a `stage` property like so:

  ```diff
  # graphcool.yml
  service: graphql-boilerplate

  + stage: dev

  datamodel: database/datamodel.graphql

  disableAuth: true
  ```

* **General stability improvements**

  Thanks to the great help and feedback we've received since the last beta release, we were able to iron out a bunch of issues. Thanks a lot :pray:

### Upgrading to beta4

* First, export your data `graphcool export -e export.zip`
* Get the latest CLI version with `npm install -g graphcool@beta`
* Then, upgrade your Docker containers using `graphcool local upgrade`
* Because of changes to the underlying data structure, you need to **completely wipe your Docker containers including all data** with `graphcool local nuke`
* Then, deploy your service again using `graphcool deploy`. You'll be prompted to choose a cluster.
* Now import the previously exported data `graphcool import -d export.zip`

### Notes

* As a reminder, **all deployed services to the `shared-public-demo` cluster are completely publically available**. The same is true for _public_ deployments to `graphcool-eu1` and `graphcool-us1`. However, for _private_ deployments (after logging in), proper [cluster authentication](https://github.com/graphcool/framework/issues/1365) is set in place, that protects both your data and services from outside access, if protected with a secret as described in the feature request.

### Resources & Feedback

* All **boilerplate examples** have been updated to the latest beta release. You can get started like this:

```sh
npm install -g graphql-cli
graphql create my-app
# choose a boilerplate and follow along the instructions
```

* The **[reference documentation](https://www.graph.cool/docs/1.0/reference/)** is continuously being updated as well.

If you have any questions or want to provide feedback, please [join the discussion in the Forum](https://www.graph.cool/forum/t/developer-preview-graphcool-1-0-beta/1891?u=nilan).

To report a bug, please use the [issue tracker](https://github.com/graphcool/graphcool).

**Pull request merged**
